// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo_List_WebApp_Pulyala.Models;

#nullable disable

namespace ToDo_List_WebApp_Pulyala.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20260325003434_SeedInitialTickets")]
    partial class SeedInitialTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDo_List_WebApp_Pulyala.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<int>("SprintNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create the MVC app and folders",
                            Name = "Setup Project Structure",
                            PointValue = 3,
                            SprintNumber = 1,
                            Status = "Done"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build Create/Read/Update/Delete logic",
                            Name = "Implement CRUD",
                            PointValue = 5,
                            SprintNumber = 1,
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fix header CSS",
                            Name = "Fix Header CSS",
                            PointValue = 1,
                            SprintNumber = 2,
                            Status = "To Do"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
